project_id = "qsipvqfqbaxmrpbmlylf"

[auth]
enable_signup = true
enable_confirmations = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes_enabled = false
enable_confirmations = false